#ifndef MATMUL_UTIL_H
#define MATMUL_UTIL_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/errno.h>

#define MAX_LEN 40960

#ifdef _WIN32

#include <windows.h>

DWORD start, end;
#define TIMER_START start = GetTickCount();
#define TIMER_END end = GetTickCount();        \
                  printf("Time spent: %.5fs\n",\
                  (end - start) / 1000.f);
#else

#include <sys/time.h>

#define US_PER_SEC 1000000.f

struct timeval start, end;
#define TIMER_START gettimeofday(&start, NULL);
#define TIMER_END gettimeofday(&end, NULL);     \
                   printf("Time spent: %.5fs\n",\
                   end.tv_sec - start.tv_sec +  \
                  (end.tv_usec - start.tv_usec) / US_PER_SEC);
#endif

/**
 * General input file validity check
 */
FILE *OpenFile(const char *filename);

/**
 * The buffer (char*) has a max length and can be reused in many calls
 * here we must assume the length of a line is shorter than this
 *
 * @param f a txt file that contains a float matrix
 * @param buf generated by the caller, let the size be 40960
 * @return the column size of input
 */
size_t CheckCol(FILE *f, char *buf);

/**
 * Scan a line each time (assume the buffer is long enough)
 * until reaches EOF
 *
 * @param f a txt file that contains a float matrix
 * @param buf generated by the caller, let the size be 40960
 * @return the row size of input
 */
size_t CheckRow(FILE *, char *buf);

#endif //MATMUL_UTIL_H
